[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rayon = "1.7"

[[bin]]
name = "ga"
path = "src/main_ga.rs"

[[bin]]
name = "two_opt"
path = "src/main_two_opt.rs"

