[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rayon = "1.7"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main_scalability"
path = "src/main_scalability.rs"

[[bin]]
name = "main_parallelism"
path = "src/main_parallelism.rs"
